#!/data/aidd-server/miniconda3/envs/Drug_Design_Backend_Release/bin/python
import sys
import os

if os.environ.get('LC_CTYPE', '') == 'UTF-8':
    os.environ['LC_CTYPE'] = 'en_US.UTF-8'
import xdalgorithm.clidriver


def main():
    return xdalgorithm.clidriver.main()


if __name__ == '__main__':
    sys.exit(main())
