ROOT_PATH_VAR='/data/aidd-server'
MGLPY_VAR = '/data/aidd-server/Modules/mgltools_x86_64Linux2_1.5.6/bin/python'
MGLUTIL_VAR = '/data/aidd-server/Modules/mgltools_x86_64Linux2_1.5.6/MGLToolsPckgs/AutoDockTools/Utilities24'
JAVA_HOME_VAR = '/data/aidd-server/jdk-14.0.2'
MODULE_HOME_VAR = '/data/aidd-server/Modules'
