
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-12-02T08:00:46+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2e3e134438f1a5f75053c2846f23f61fda9397c3",
 "version": "2.0.0+248.g2e3e1344"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
